spring:
#  security:
#    enabled: false
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa.show-sql: true

  data:
    rest:
      basePath:  /api
keycloak:
  realm: master
  resource: demo
  auth-server-url: http://swagger-ui:8084/auth
  ssl-required: external
  public-client: true
#  securityConstraints:
#    - securityCollections:
#      - name: application section
#        authRoles:
#            - user
#        patterns:
#            - /

#server:
#  servlet:
#    context-path: /demo

#security:
#  ignored: /**
#  basic:
#    enabled: false
#management:
#  security:
#    enabled: false